"""agregar niveles de heroe a miembros capturados

Revision ID: a6f9d5abb349
Revises: 4b9336b32128
Create Date: 2026-10-03 13:36:10.617440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f9d5abb349'
down_revision: Union[str, Sequence[str], None] = '4b9336b32128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capturas_miembros', sa.Column('nivel_rey_barbaro', sa.Integer(), nullable=True))
    op.add_column('capturas_miembros', sa.Column('nivel_reina_arquera', sa.Integer(), nullable=True))
    op.add_column('capturas_miembros', sa.Column('nivel_gran_centinela', sa.Integer(), nullable=True))
    op.add_column('capturas_miembros', sa.Column('nivel_principe_esbirro', sa.Integer(), nullable=True))
    op.add_column('capturas_miembros', sa.Column('nivel_luchadora_real', sa.Integer(), nullable=True))
    op.add_column('capturas_miembros', sa.Column('nivel_duque_dragon', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capturas_miembros', 'nivel_duque_dragon')
    op.drop_column('capturas_miembros', 'nivel_luchadora_real')
    op.drop_column('capturas_miembros', 'nivel_principe_esbirro')
    op.drop_column('capturas_miembros', 'nivel_gran_centinela')
    op.drop_column('capturas_miembros', 'nivel_reina_arquera')
    op.drop_column('capturas_miembros', 'nivel_rey_barbaro')
    # ### end Alembic commands ###
